import type { Metadata } from 'next'
import './globals.css'
import { Epilogue } from 'next/font/google'
import { Providers } from '@/components/providers'
import { getLocale, getMessages } from 'next-intl/server'

const epilogue = Epilogue({
  subsets: ['latin'],
  variable: '--font-epilogue',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  const messages = await getMessages()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${epilogue.variable} antialiased font-epilogue`}>
        <Providers messages={messages}>{children}</Providers>
      </body>
    </html>
  )
}
